version: '3.8'

services:
  ipea-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BUCKET_NAME=${BUCKET_NAME:-}
    volumes:
      - ./:/app
    restart: "no"
    command: python /app/main.py