name: "Security Scan"

on:
  workflow_call:

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          vulnerability-threshold: 'MEDIUM'
